### ISSUE TITLE
Search Button

### ISSUE THREAD

**Issue by JOHN748** [debascoguy/FlexiblePaginationJS#3]
Hey...Thanks fr this plugin. I have one question how can i change search filter (keyup) method to onclick button search method.

For example i've entering some text values in input field then it will filter the contents... I want that to filter when i click the button called search. How can i do that. Pls help.

**Comment by debascoguy** [comment]
Hello their,
Per your request, I have updated the Library to allow the search serve your need.
Please review the example.html to see sample usage.

You can now disable the search (keyup) method by enabling the 'onClick' option of search parameter to 'true'.
That is, 

search { onClick: true,   onClickSelector: '#myCommandButton'    }

Please note: the 'onClickSelector' field can be a css class.

Thanks and Enjoy.

**Comment by JOHN748** [comment]
Good Job brother 🤓....Thanks for the quick reply.

**Comment by JOHN748** [comment]
Bro i've done what you said but it doesn't work....I made changes to my file as per you said after changes Search and pagination both are not working now.... Can you please share your running example in codepen or Jsfiddle or any other Online compiler.  Please.

**Comment by debascoguy** [comment]
Sorry I have made some initialization fixes. You can download the latest version now and all should be good.

**Comment by JOHN748** [comment]
Sry for the disturbance bro,  My contents Automaticaly filtering by keyup method onclick button search method not working....ill attach Code and my codepen link pls tell is there any mistake i did

Codepen link : https://codepen.io/JOHNakl/pen/mdJZEKN

HTML 
`<input class="searchBox form-control" placeholder="Search Something. E.g. jQueryScript">
   <button id="butop">Search</button>`

JS
`var flexiblePagination = $('#content').flexiblePagination({
            itemsPerPage : 2,
            displayedPages: 3,
            itemSelector : 'div.result:visible',
            pagingControlsContainer : '#pagingControls',
            showingInfoSelector : '#showingInfo',
            css: {
                btnNumberingClass: 'btn btn-sm btn-success',
                btnFirstClass: 'btn btn-sm btn-success',
                btnLastClass: 'btn btn-sm btn-success',
                btnNextClass: 'btn btn-sm btn-success',
                btnPreviousClass: 'btn btn-sm btn-success'
            },
            search: {
                onClick: true,
                onClickSelector: '#butop'
            }
        });
        flexiblePagination.getController().onPageClick = function(pageNum, e){
            console.log('You Clicked Page: '+pageNum)
        };
    });`

**Comment by debascoguy** [comment]
Hey man, No problem at all. I have been rushing through things... I saw it clearly through your codepen and realized that the search parameters where overwritten by another function inside the library due to naming conflicts. Anyways, the issue is definitely resolved. Please check the example.html for the new naming of the search param.

searchBox{...}

**Comment by JOHN748** [comment]
Yup....Working bro 😍
