### ISSUE TITLE
Show search results on new Page

### ISSUE THREAD

**Issue by JOHN748** [debascoguy/FlexiblePaginationJS#5]
Hey bro, i'm doing one php project in that i have to show all the item results to new page (that is in search page) with pagination. Please help ! Waiting for your response. Ty

**Comment by JOHN748** [comment]
Brother , Waiting for your reply. Pls help

**Comment by debascoguy** [comment]
are you familiar with Ajax calls? 
are you using any frontend technology like angular/react (not a must)?
If no frontend technology and you are familiar with Ajax calls. let me know and we can work out suitable solution.

**Comment by JOHN748** [comment]
No bro i don't know those languages

**Comment by JOHN748** [comment]
Bro any solution ?
